# Generated by Django 3.1.7 on 2021-03-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210310_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='to_date',
            field=models.DateField(blank=True, null=True, verbose_name='to_date'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
