# Generated by Django 3.1.7 on 2021-03-10 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210310_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companies',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
