# Generated by Django 3.1.7 on 2021-03-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210310_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_name', models.CharField(max_length=70)),
                ('event_date', models.DateField(verbose_name='Event Date')),
                ('event_org', models.CharField(max_length=30, verbose_name='Event Organizer')),
                ('certificate', models.ImageField(upload_to='')),
                ('position', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
