# Generated by Django 3.1.7 on 2021-03-11 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210311_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designations',
            name='company',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='designation',
        ),
        migrations.AddField(
            model_name='companies',
            name='designation_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.designations'),
        ),
    ]
